---
apiVersion: v1
kind: Service
metadata:
  name: trust-calc
  labels:
    name: trust-calc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30999
  selector:
    name: trust-calc
